apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: tomcat-pod
spec:
 replicas: 5
 selector:
   matchLabels:
     type: webserver
 template:
    metadata:
       name: tomcat-pod
       labels:
          type: webserver
       spec:
          containers:
            - name: mytomcat
              image: tomcat
              port:
               - containerPort: 8080
                 hostPort: 9090
